---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	step1(step1)
	step2(step2)
	human_feedback(human_feedback<hr/><small><em>__interrupt = before</em></small>)
	step3(step3)
	__end__([<p>__end__</p>]):::last
	__start__ --> step1;
	human_feedback --> step3;
	step1 --> step2;
	step2 --> human_feedback;
	step3 --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
